### ISSUE TITLE
Project description Mode of operation issue

### ISSUE THREAD

**Issue by Priyansu122** [silicon-efabless/tt06-silicon-tinytapeout-lm07#5]
In project description The mode of operation truth table :

ui_in[0]	ui_in[1]    ui_in[2] 
0	0	 0		 MSB Onboard Display in C
0	1	 0	         LSB Onboard Display in C
0	0	 1	         MSB Onboard Display in F	
0	1	 1              LSB Onboard Display in F
1      X      0              External 7 segemnt in C
1      X      1              External 7 segemnt in F

**Comment by silicon-vlsi** [comment]
Fixed. Thanks.
